INTEGER, BOOL, STRING, PLUS, MINUS, MULTIPLY, DIVIDE, LPAREN, RPAREN, EOF, NEGATE = 'INTEGER', 'BOOL', 'STRING', 'PLUS', 'MINUS', 'MULTIPLY', 'DIVIDE', 'LPAREN', 'RPAREN', 'EOF', 'NEGATE'
OPERATORS = {PLUS: 1, MINUS: 1, MULTIPLY: 2, DIVIDE: 2}  # Operator precedence
TYPES = {INTEGER, BOOL, STRING}